#!/bin/bash

set -euo pipefail

MOUNT_ROOT="${AEGISOS_MOUNT_ROOT:-/mnt/aegisos-target}"
TARGET_DISK=""
ADMIN_USER=""
ADMIN_PASSWORD=""

partition_path() {
    local disk="$1"
    local number="$2"

    if [[ "$disk" =~ [0-9]$ ]]; then
        printf '%sp%s\n' "$disk" "$number"
    else
        printf '%s%s\n' "$disk" "$number"
    fi
}

need_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required installer command: $1" >&2
        exit 1
    fi
}

cleanup() {
    set +e
    for path in \
        "$MOUNT_ROOT/run" \
        "$MOUNT_ROOT/sys" \
        "$MOUNT_ROOT/proc" \
        "$MOUNT_ROOT/dev" \
        "$MOUNT_ROOT/boot/efi" \
        "$MOUNT_ROOT"; do
        if mountpoint -q "$path"; then
            umount -R "$path"
        fi
    done
}

normalize_disk() {
    local input="$1"

    if [[ "$input" != /dev/* ]]; then
        input="/dev/$input"
    fi
    readlink -f "$input"
}

validate_disk() {
    local disk="$1"
    local mounted

    [[ -b "$disk" ]] || {
        echo "Invalid block device: $disk" >&2
        return 1
    }
    [[ "$(lsblk -dnro TYPE "$disk")" == "disk" ]] || {
        echo "Target must be a whole disk: $disk" >&2
        return 1
    }
    [[ "$(lsblk -dnro RO "$disk")" == "0" ]] || {
        echo "Target disk is read-only: $disk" >&2
        return 1
    }

    mounted="$(lsblk -nrpo MOUNTPOINT "$disk" | awk 'NF { print; exit }')"
    [[ -z "$mounted" ]] || {
        echo "Target disk has mounted filesystems: $mounted" >&2
        return 1
    }
}

validate_admin_username() {
    local username="$1"

    [[ "$username" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]] || {
        echo "Administrator username must use lowercase letters, digits, _ or -." >&2
        return 1
    }
    case "$username" in
        root|aegis|aegis-live)
            echo "Reserved administrator username: $username" >&2
            return 1
            ;;
    esac
}

validate_admin_password() {
    local password="$1"

    [[ ${#password} -ge 12 ]] || {
        echo "Administrator password must be at least 12 characters." >&2
        return 1
    }
    [[ "$password" != *:* &&
       "$password" != *$'\n'* &&
       "$password" != *$'\r'* ]] || {
        echo "Administrator password contains unsupported characters." >&2
        return 1
    }
}

read_admin_credentials() {
    local confirmation

    if [[ -n "${AEGISOS_ADMIN_USER:-}" ||
          -n "${AEGISOS_ADMIN_PASSWORD:-}" ]]; then
        [[ -n "${AEGISOS_ADMIN_USER:-}" &&
           -n "${AEGISOS_ADMIN_PASSWORD:-}" ]] || {
            echo "Set both AEGISOS_ADMIN_USER and AEGISOS_ADMIN_PASSWORD." >&2
            return 1
        }
        ADMIN_USER="$AEGISOS_ADMIN_USER"
        ADMIN_PASSWORD="$AEGISOS_ADMIN_PASSWORD"
    else
        read -r -p "Administrator username: " ADMIN_USER
        read -r -s -p "Administrator password: " ADMIN_PASSWORD
        echo
        read -r -s -p "Confirm administrator password: " confirmation
        echo
        [[ "$ADMIN_PASSWORD" == "$confirmation" ]] || {
            echo "Administrator passwords do not match." >&2
            return 1
        }
    fi

    validate_admin_username "$ADMIN_USER"
    validate_admin_password "$ADMIN_PASSWORD"
}

configure_target_accounts() {
    if chroot "$MOUNT_ROOT" getent passwd "$ADMIN_USER" >/dev/null; then
        echo "Administrator account already exists: $ADMIN_USER" >&2
        return 1
    fi

    if chroot "$MOUNT_ROOT" getent passwd aegis-live >/dev/null; then
        chroot "$MOUNT_ROOT" userdel --remove aegis-live
    fi
    rm -f "$MOUNT_ROOT/etc/sudoers.d/aegis-live"
    sed -i '/^[[:space:]]*Live login:/d' "$MOUNT_ROOT/etc/motd"

    chroot "$MOUNT_ROOT" useradd --create-home --shell /bin/bash \
        --groups sudo "$ADMIN_USER"
    printf '%s:%s\n' "$ADMIN_USER" "$ADMIN_PASSWORD" |
        chroot "$MOUNT_ROOT" chpasswd
    chroot "$MOUNT_ROOT" passwd --lock root
}

write_fstab() {
    local efi_partition="$1"
    local root_partition="$2"
    local efi_uuid root_uuid

    efi_uuid="$(blkid -s UUID -o value "$efi_partition")"
    root_uuid="$(blkid -s UUID -o value "$root_partition")"
    [[ -n "$efi_uuid" && -n "$root_uuid" ]] || {
        echo "Unable to determine filesystem UUIDs" >&2
        return 1
    }

    cat > "$MOUNT_ROOT/etc/fstab" <<EOF
# /etc/fstab generated by the AegisOS installer.
UUID=$root_uuid / ext4 defaults,errors=remount-ro 0 1
UUID=$efi_uuid /boot/efi vfat umask=0077 0 1
EOF
}

write_grub_defaults() {
    local grub_defaults="$MOUNT_ROOT/etc/default/grub"

    touch "$grub_defaults"
    sed -i \
        -e '/^GRUB_TERMINAL=/d' \
        -e '/^GRUB_SERIAL_COMMAND=/d' \
        -e '/^GRUB_CMDLINE_LINUX_DEFAULT=/d' \
        "$grub_defaults"
    cat >> "$grub_defaults" <<'EOF'
GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1"
GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200"
EOF
}

install_system() {
    local disk="$1"
    local efi_partition bios_partition root_partition

    efi_partition="$(partition_path "$disk" 1)"
    bios_partition="$(partition_path "$disk" 2)"
    root_partition="$(partition_path "$disk" 3)"

    echo "Partitioning $disk..."
    wipefs -a "$disk"
    parted -s "$disk" mklabel gpt
    parted -s "$disk" mkpart ESP fat32 1MiB 513MiB
    parted -s "$disk" set 1 esp on
    parted -s "$disk" mkpart BIOS 513MiB 515MiB
    parted -s "$disk" set 2 bios_grub on
    parted -s "$disk" mkpart AegisOS ext4 515MiB 100%
    partprobe "$disk"
    udevadm settle

    [[ -b "$efi_partition" && -b "$bios_partition" && -b "$root_partition" ]] || {
        echo "Partition devices did not appear" >&2
        return 1
    }

    echo "Formatting filesystems..."
    mkfs.fat -F 32 -n AEGIS_EFI "$efi_partition"
    mkfs.ext4 -F -L AEGIS_ROOT "$root_partition"

    mkdir -p "$MOUNT_ROOT"
    mount "$root_partition" "$MOUNT_ROOT"
    mkdir -p "$MOUNT_ROOT/boot/efi"
    mount "$efi_partition" "$MOUNT_ROOT/boot/efi"

    echo "Copying system..."
    rsync -aHAX --numeric-ids \
        --exclude=/dev/* \
        --exclude=/proc/* \
        --exclude=/sys/* \
        --exclude=/run/* \
        --exclude=/tmp/* \
        --exclude=/mnt/* \
        --exclude=/media/* \
        --exclude=/live/* \
        --exclude=/cdrom/* \
        / "$MOUNT_ROOT/"

    for path in dev proc sys run tmp; do
        mkdir -p "$MOUNT_ROOT/$path"
    done
    chmod 1777 "$MOUNT_ROOT/tmp"
    write_fstab "$efi_partition" "$root_partition"
    echo aegisos > "$MOUNT_ROOT/etc/hostname"
    write_grub_defaults
    configure_target_accounts

    mount --rbind /dev "$MOUNT_ROOT/dev"
    mount --make-rslave "$MOUNT_ROOT/dev"
    mount --types proc proc "$MOUNT_ROOT/proc"
    mount --rbind /sys "$MOUNT_ROOT/sys"
    mount --make-rslave "$MOUNT_ROOT/sys"
    mount --rbind /run "$MOUNT_ROOT/run"
    mount --make-rslave "$MOUNT_ROOT/run"

    echo "Installing bootloaders..."
    chroot "$MOUNT_ROOT" grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id=AegisOS \
        --removable \
        --no-nvram \
        --recheck
    chroot "$MOUNT_ROOT" grub-install \
        --target=i386-pc \
        --recheck \
        "$disk"
    chroot "$MOUNT_ROOT" update-grub

    : > "$MOUNT_ROOT/etc/machine-id"
    rm -f "$MOUNT_ROOT/var/lib/dbus/machine-id"
    ln -s /etc/machine-id "$MOUNT_ROOT/var/lib/dbus/machine-id"
    rm -f "$MOUNT_ROOT"/etc/ssh/ssh_host_*
    chroot "$MOUNT_ROOT" ssh-keygen -A
    chroot "$MOUNT_ROOT" systemctl enable aegisosd guardian ssh ufw

    sync
    cleanup
}

main() {
    local answer disk_input

    if [[ "${1:-}" == "--partition-path" ]]; then
        [[ $# -eq 3 ]] || {
            echo "Usage: $0 --partition-path DISK NUMBER" >&2
            exit 2
        }
        partition_path "$2" "$3"
        exit 0
    fi
    if [[ "${1:-}" == "--validate-admin-username" ]]; then
        [[ $# -eq 2 ]] || {
            echo "Usage: $0 --validate-admin-username USERNAME" >&2
            exit 2
        }
        validate_admin_username "$2"
        exit 0
    fi

    [[ "$(id -u)" -eq 0 ]] || {
        echo "The installer must run as root." >&2
        exit 1
    }
    for command in \
        blkid chroot grub-install lsblk mkfs.ext4 mkfs.fat mount mountpoint \
        parted partprobe readlink rsync ssh-keygen udevadm umount \
        update-grub wipefs; do
        need_command "$command"
    done

    trap cleanup EXIT
    trap 'exit 130' INT TERM
    clear
    echo "=== AegisOS 0.3 Installer ==="
    echo "WARNING: This will erase the selected target disk."
    echo
    lsblk -d -o NAME,SIZE,MODEL,TYPE | awk 'NR == 1 || $NF == "disk"'
    echo

    if [[ -n "${AEGISOS_INSTALL_DISK:-}" ]]; then
        disk_input="$AEGISOS_INSTALL_DISK"
    else
        read -r -p "Target disk (for example vda or nvme0n1): " disk_input
    fi
    TARGET_DISK="$(normalize_disk "$disk_input")"
    validate_disk "$TARGET_DISK"

    if [[ "${AEGISOS_INSTALL_CONFIRM:-}" != "yes" ]]; then
        read -r -p "Erase ALL data on $TARGET_DISK? Type yes: " answer
        [[ "$answer" == "yes" ]] || {
            echo "Installation cancelled."
            exit 0
        }
    fi

    read_admin_credentials
    install_system "$TARGET_DISK"
    ADMIN_PASSWORD=""
    trap - EXIT INT TERM
    echo "AegisOS installation completed successfully for $ADMIN_USER."

    if [[ "${AEGISOS_INSTALL_POWEROFF:-}" == "yes" ]]; then
        answer="yes"
    else
        read -r -p "Power off now? [Y/n]: " answer
    fi
    if [[ -z "$answer" || "$answer" =~ ^[Yy]([Ee][Ss])?$ ]]; then
        systemctl --no-block poweroff ||
            systemctl --force --force poweroff ||
            poweroff -f
    fi
}

main "$@"
